...

diff --git a/python-ci.yml b/python-ci.yml
--- a/python-ci.yml
+++ b/python-ci.yml
@@ -3,37 +3,34 @@ name: Python CI
 on:
   push:
     branches:
-      - master
-      - dev2
+      - main
 
 jobs:
-  build:
-    runs-on: windows-latest
+  test:
+    runs-on: window-latest
 
-    steps:
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.x
-
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        
-
-    - name: Run tests
-      run: |
-        python -m unittest discover -s tests
-
-  on-failure:
-    runs-on: windows-latest
-    needs: build
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Create failure branch
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: 3.8
+
+    - name: Install dependencies
       run: |
-        git checkout -B failure-branch
-        git commit --allow-empty -m "Failure branch for failed tests"
-        git push origin failure-branch
+        python -m pip install --upgrade pip
+
+    - name: Run tests
+      run: |
+        if python -m unittest tests/ConvertisseurNombresRomains_test.py; then
+          echo "Tests passed!"
+        else
+          echo "Tests failed. Creating failure branch..."
+          git checkout -b failure-branch
+          git commit --allow-empty -m "Failure branch for failed tests"
+          git push origin failure-branch
+          echo "Failure branch created and pushed."
+          exit 1
+        fi
